In [1]:
import random
import pandas as pd

In [2]:
departments = ['Organization', 'Police', 'Propagation', 'Military', 'Law', 'Industry']

def random_major(majors=departments):
    return random.choice(majors)

def random_name(region=None, k=None):
    if region is None:
        region = [chr(e) for e in range(ord('a'), ord('z')+1)]
    if k is None:
        k = [random.randint(3, 5), random.randint(5, 10)]
    xing = ''.join(random.choices(region, k=k[0])).title()
    ming = ''.join(random.choices(region, k=k[1])).title()
    return ' '.join([xing, ming])

def random_age(low=40, high=75):
    return random.randint(low, high)

def level3_uid(idx):
    return 'L3-{idx:04d}'.format(idx=idx)

In [3]:
num_level3 = 100

In [4]:
level3_df = pd.DataFrame(columns=['name', 'major', 'age', 'uid'])
level3_df

Empty DataFrame
Columns: [name, major, age, uid]
Index: []

In [5]:
for _ in range(num_level3):
    uid = level3_uid(_)
    info = dict(
        major = random.choice(departments),
        name = random_name(),
        age = random_age(),
        uid = uid
    )
    level3_df = level3_df.append(pd.Series(info, name=uid))
level3_df

                     name         major age      uid
L3-0000        Sit Dikywz      Military  47  L3-0000
L3-0001    Ulub Jipgrgius        Police  67  L3-0001
L3-0002        Fqv Rhdxel   Propagation  54  L3-0002
L3-0003    Dcy Kzdmhoajtr  Organization  47  L3-0003
L3-0004    Swbzv Pgnydwna      Military  65  L3-0004
...                   ...           ...  ..      ...
L3-0095     Qcjwt Vrourrn      Military  43  L3-0095
L3-0096        Lvsx Kfjzm        Police  41  L3-0096
L3-0097  Glhrw Ovfuhkzqct      Industry  70  L3-0097
L3-0098    Fvk Bbwwhxebwv        Police  57  L3-0098
L3-0099     Vppr Veommgew           Law  63  L3-0099

[100 rows x 4 columns]

In [6]:
level3_df.loc[level3_df['major'] == 'Industry']

                     name     major age      uid
L3-0007    Wnbh Lpbohwzmc  Industry  54  L3-0007
L3-0012    Fbh Flixqaqbwb  Industry  43  L3-0012
L3-0015    Wxkgd Upnnojku  Industry  59  L3-0015
L3-0022      Fht Awhknroz  Industry  63  L3-0022
L3-0035     Fpz Uhkhhgicw  Industry  46  L3-0035
L3-0045      Peu Ufuyhcfh  Industry  50  L3-0045
L3-0052      Nqg Fvpoumss  Industry  48  L3-0052
L3-0061     Faufy Ckzlseq  Industry  72  L3-0061
L3-0091         Ljl Kazdk  Industry  45  L3-0091
L3-0097  Glhrw Ovfuhkzqct  Industry  70  L3-0097

In [7]:
level3_df.loc[level3_df['age'].isin(range(55, 60))]

                     name         major age      uid
L3-0009    Jryig Yulcobzo        Police  58  L3-0009
L3-0010       Htcz Zstitt           Law  58  L3-0010
L3-0015    Wxkgd Upnnojku      Industry  59  L3-0015
L3-0018   Airo Baxhjiddiy   Propagation  55  L3-0018
L3-0021       Htd Petrilc      Military  57  L3-0021
L3-0025       Wym Waoyaub  Organization  55  L3-0025
L3-0027  Oeadk Lkcxwkrmnc  Organization  58  L3-0027
L3-0033    Divo Tnwaxtpxs        Police  56  L3-0033
L3-0039     Cfd Mbhbyqdpu   Propagation  55  L3-0039
L3-0041     Uektv Vsdvbxj   Propagation  55  L3-0041
L3-0049       Utzyd Tnsnu  Organization  58  L3-0049
L3-0057      Kdj Otdvuvhx        Police  55  L3-0057
L3-0060     Pgtni Paafuop   Propagation  57  L3-0060
L3-0066      Efeaw Rpgmzf   Propagation  57  L3-0066
L3-0067  Rzxrf Qzrjikdypw           Law  57  L3-0067
L3-0070     Anwzs Rjlcjuc  Organization  57  L3-0070
L3-0072    Xnrj Ssyltufgx      Military  57  L3-0072
L3-0075   Xoupr Gyofagwcq      Military  56  L3-0075
L3-0076         Lpj Roief  Organization  56  L3-0076
L3-0093   Cmiza Bfhvkyrdx        Police  58  L3-0093
L3-0098    Fvk Bbwwhxebwv        Police  57  L3-0098

In [18]:
level3_df.to_json('level3.json')  # , orient='records')